spring:
  main:
    web-environment: true
    show-banner: false
  datasource:
    url: "jdbc:mysql://localhost:3306/aa_model_service?autoReconnect=true"
    username: "root"
    password: ""
    maximum-pool-size: 8
    minimum-idle: 0
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    openInView: true
    database: "MYSQL"
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
  data:
    rest:
      base-path: "/api"
endpoints:
  health:
    sensitive: false
management:
  context-path: "/admin"
  metrics:
    export:
      jmx:
        domain: spring
    enable:
      jvm: false
      tomcat: false
      system: false
      process: false
elasticsearch:
  clusterName: elasticsearch_kashah
  hostName: localhost
  port: 9300

graphite:
  urlTemplate: "https://graphite.test.monitoring.expedia.com/render?from=-24hours&format=json&maxDataPoints=144&target=seriesByTag('{tags}')"
security:
  clientId: "id"
  secret: "secret"
  signingKey: "1234"
server:
  port: 8080
