spring:
  main:
    web-environment: true
    show-banner: false
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://database:3306/aa_model_service?autoReconnect=true"
    username: "root"
    password: ""
    maximum-pool-size: 8
    minimum-idle: 0
  jpa:
    openInView: true
    database: "MYSQL"
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
  data:
    rest:
      base-path: "/api"
endpoints:
  health:
    sensitive: false
management:
  context-path: "/admin"
graphite:
  urlTemplate: "https://graphite.test.monitoring.expedia.com/render?from=-168hours&format=json&maxDataPoints=1008&target={target}"
security:
  signingKey: "key"
server:
  port: 8008
